### ISSUE TITLE
Stuck at Checking Ip (Linux)

### ISSUE THREAD

**Issue by devlevellops** [bepass-org/oblivion-desktop#491]
### Attention | توجه

- [ ] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

I'm using Manjaro Linux now. It keep getting stuck on checking IP.
![Screenshot_2024-08-17_17-02-16](https://github.com/user-attachments/assets/15bf117d-8a51-488a-85dc-d568081f12c6)

### Relevant log output | لاگ برنامه

```shell
[2024-08-17 16:44:42.568] [info]  past logs was deleted for new connection.
[2024-08-17 16:44:42.573] [info]  ------------------------MetaData------------------------
[2024-08-17 16:44:42.573] [info]  running on: linux 6.1.11-1-MANJARO x64
[2024-08-17 16:44:42.574] [info]  at od: 1.1.0
[2024-08-17 16:44:42.574] [info]  at wp: v1.2.4
[2024-08-17 16:44:42.575] [info]  ls assets/bin: LICENSE,README.md,warp-plus
[2024-08-17 16:44:42.576] [info]  method: gool
[2024-08-17 16:44:42.576] [info]  proxyMode: true
[2024-08-17 16:44:42.577] [info]  routingRules: Default
[2024-08-17 16:44:42.577] [info]  endpoint: default
[2024-08-17 16:44:42.578] [info]  license: false
[2024-08-17 16:44:42.578] [info]  exe: /home/<USERNAME>/Games/oblivion-desktop-linux-x64/oblivion-desktop
[2024-08-17 16:44:42.579] [info]  userData: /home/<USERNAME>/.config/oblivion-desktop
[2024-08-17 16:44:42.579] [info]  logs: /home/<USERNAME>/.config/oblivion-desktop/logs
[2024-08-17 16:44:42.580] [info]  ------------------------MetaData------------------------
[2024-08-17 16:44:42.590] [info]  starting wp process...
[2024-08-17 16:44:42.590] [info]  /home/<USERNAME>/.config/oblivion-desktop/warp-plus --bind 127.0.0.1:8086 --gool --scan --rtt 1s --dns 1.1.1.1
[2024-08-17 16:44:42.599] [info]  trying to set system proxy...
[2024-08-17 16:44:42.605] [info]  gsettings found!
time=2024-08-17T16:44:42.602+08:00 level=INFO msg="scanner mode enabled" max-rtt=1s
time=2024-08-17T16:44:42.603+08:00 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

[2024-08-17 16:44:42.628] [info]  Gnome old proxy host : '127.0.0.1'

[2024-08-17 16:44:42.634] [info]  Gnome old proxy port : 8086

[2024-08-17 16:44:42.848] [info]  Enabled proxy for GNOME.
time=2024-08-17T16:44:44.171+08:00 level=ERROR msg="ping error" subsystem=scanner addr=2606:4700:d1:0:db01:a985:d05c:21eb error="dial udp [2606:4700:d1:0:db01:a985:d05c:21eb]:5956: connect: network is unreachable"

time=2024-08-17T16:44:46.604+08:00 level=INFO msg="using warp endpoints" endpoints="[188.114.99.15:1387 162.159.192.31:8742]"
time=2024-08-17T16:44:46.604+08:00 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-08-17T16:44:46.604+08:00 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-08-17T16:44:53.226+08:00 level=INFO msg="connection test successful"

time=2024-08-17T16:44:53.227+08:00 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-08-17T16:44:54.879+08:00 level=INFO msg="connection test successful"

time=2024-08-17T16:44:54.880+08:00 level=INFO msg="serving proxy" address=127.0.0.1:8086
```

**Comment by ircfspace** [comment]
The issue with displaying ping before a successful connection has been fixed in the latest version of the app. Regarding the connection problem, it's recommended to test with the suggested endpoints.

https://github.com/bepass-org/oblivion-desktop/releases

**Comment by devlevellops** [comment]
Still the same problem after i update to 1.6.6
![Screenshot_2024-08-18_14-54-08](https://github.com/user-attachments/assets/8c835dbf-1b92-417f-9a01-d39e1a0410b3)

`[2024-08-18 14:49:05.894] [info]  past logs was deleted for new connection.
[2024-08-18 14:49:05.905] [info]  ------------------------MetaData------------------------
[2024-08-18 14:49:05.906] [info]  running on: linux 6.1.11-1-MANJARO x64
[2024-08-18 14:49:05.906] [info]  at od: 1.6.6
[2024-08-18 14:49:05.906] [info]  at wp: v1.2.4
[2024-08-18 14:49:05.906] [info]  ls assets/bin: LICENSE,README.md,warp-plus
[2024-08-18 14:49:05.907] [info]  method: gool
[2024-08-18 14:49:05.907] [info]  proxyMode: true
[2024-08-18 14:49:05.907] [info]  routingRules: Default
[2024-08-18 14:49:05.907] [info]  endpoint: default
[2024-08-18 14:49:05.907] [info]  asn: UNK
[2024-08-18 14:49:05.907] [info]  license: false
[2024-08-18 14:49:05.907] [info]  exe: /home/<USERNAME>/Games/oblivion-desktop-linux-x64/OblivionDesktop
[2024-08-18 14:49:05.908] [info]  userData: /home/<USERNAME>/.config/oblivion-desktop
[2024-08-18 14:49:05.908] [info]  logs: /home/<USERNAME>/.config/oblivion-desktop/logs
[2024-08-18 14:49:05.908] [info]  ------------------------MetaData------------------------
[2024-08-18 14:49:05.908] [info]  starting wp process...
[2024-08-18 14:49:05.908] [info]  /home/<USERNAME>/.config/oblivion-desktop/warp-plus --bind 127.0.0.1:8086 --gool --scan --rtt 1s
[2024-08-18 14:49:05.917] [info]  trying to set system proxy...
[2024-08-18 14:49:05.924] [info]  gsettings found!
time=2024-08-18T14:49:05.920+08:00 level=INFO msg="scanner mode enabled" max-rtt=1s
time=2024-08-18T14:49:05.920+08:00 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

[2024-08-18 14:49:05.946] [info]  Gnome old proxy host : '127.0.0.1'

[2024-08-18 14:49:05.952] [info]  Gnome old proxy port : 8086

[2024-08-18 14:49:06.181] [info]  Enabled proxy for GNOME.
time=2024-08-18T14:49:08.879+08:00 level=ERROR msg="ping error" subsystem=scanner addr=162.159.193.59 error="error sending random packet: write udp 192.168.188.11:38331->162.159.193.59:891: write: connection refused"

time=2024-08-18T14:49:08.881+08:00 level=ERROR msg="ping error" subsystem=scanner addr=2606:4700:d1:0:a02:34e1:3bfb:233b error="dial udp [2606:4700:d1:0:a02:34e1:3bfb:233b]:942: connect: network is unreachable"

time=2024-08-18T14:49:08.921+08:00 level=INFO msg="using warp endpoints" endpoints="[162.159.192.145:3476 188.114.97.49:945]"
time=2024-08-18T14:49:08.921+08:00 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-08-18T14:49:08.921+08:00 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-08-18T14:49:14.111+08:00 level=INFO msg="connection test successful"

time=2024-08-18T14:49:14.112+08:00 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-08-18T14:49:15.394+08:00 level=INFO msg="connection test successful"

time=2024-08-18T14:49:15.395+08:00 level=INFO msg="serving proxy" address=127.0.0.1:8086

`

**Comment by ircfspace** [comment]
As I mentioned in my previous message, it's necessary to review the process of connecting to custom endpoints. Please refer to the scanner settings and select the endpoint option.
